version: "3.4"

services:
  web:
    image: redis-proxy-engine
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    env_file: .env
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
